<?php

namespace App\Support;

/**
 * Mapeo central camelCase (frontend) <-> snake_case (BD) por entidad.
 * Reutilizado por los controladores, la importacion y las metricas para
 * evitar duplicar la traduccion de campos.
 */
class EntityFields
{
    public const TENDER = [
        'id' => 'id',
        'code' => 'code',
        'title' => 'title',
        'lot' => 'lot',
        'client' => 'client',
        'deadline' => 'deadline',
        'status' => 'status',
        'budget' => 'budget',
        'economicOffer' => 'economic_offer',
        'economicOfferWaived' => 'economic_offer_waived',
        'owner' => 'owner',
        'coAuthored' => 'co_authored',
        'coAuthor' => 'co_author',
        'adjudicationDate' => 'adjudication_date',
        'presentedAt' => 'presented_at',
        'description' => 'description',
    ];

    public const MILESTONE = [
        'id' => 'id',
        'title' => 'title',
        'tender' => 'tender',
        'tenderId' => 'tender_id',
        'type' => 'type',
        'preparationOther' => 'preparation_other',
        'receptionDate' => 'reception_date',
        'date' => 'date',
        'status' => 'status',
        'owner' => 'owner',
        'autoGenerated' => 'auto_generated',
    ];

    public const EXECUTION = [
        'id' => 'id',
        'tenderId' => 'tender_id',
        'signed' => 'signed',
        'startDate' => 'start_date',
        'endDate' => 'end_date',
        'frequencyMonths' => 'frequency_months',
        'milestonePayments' => 'milestone_payments',
    ];

    public const MEMBER = [
        'id' => 'id',
        'name' => 'name',
        'username' => 'username',
        'role' => 'role',
        'email' => 'email',
        'status' => 'status',
        'password' => 'password',
        'passwordResetAt' => 'password_reset_at',
        'avatar' => 'avatar',
    ];

    /** Modelo BD -> array camelCase para el frontend (incluye updatedAt para bloqueo optimista). */
    public static function toCamel($model, array $map): array
    {
        $out = [];

        foreach ($map as $camel => $column) {
            $out[$camel] = $model->getAttribute($column);
        }

        if ($model->getAttribute('updated_at') !== null) {
            $out['updatedAt'] = optional($model->getAttribute('updated_at'))->toISOString();
        }

        return $out;
    }

    /** Coleccion de modelos -> array de arrays camelCase. */
    public static function collectionToCamel($models, array $map): array
    {
        return collect($models)->map(fn ($model) => self::toCamel($model, $map))->all();
    }

    /** Payload camelCase del frontend -> atributos snake_case (solo claves presentes). */
    public static function toAttributes(array $row, array $map): array
    {
        $attributes = [];

        foreach ($map as $camel => $column) {
            if (array_key_exists($camel, $row)) {
                $attributes[$column] = $row[$camel];
            }
        }

        return $attributes;
    }
}
